"""
gen_batch5.py — Layer 1 morphology annotations for batch_5 (54 remaining ara-lat words).
Appends to Juthoor-CognateDiscovery-LV2/data/llm_annotations/layer1_morphology.jsonl
"""

import json
import pathlib

OUTFILE = pathlib.Path(__file__).parent.parent / "data" / "llm_annotations" / "layer1_morphology.jsonl"

ANNOTATIONS = [
    # album <- سجل  (Latin albus = white; a blank white tablet)
    {
        "word": "album",
        "lang": "lat",
        "actual_lang": "lat",
        "etymological_form": "album",
        "true_stem": "alb",
        "oblique_stem": None,
        "root_consonants": ["l", "b"],
        "prefixes_real": [],
        "suffixes_real": ["um"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin album (white tablet), neuter of albus (white). Originally a blank white board for public notices.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # alone <- زوج  (English word, not Latin; from Old English al one)
    {
        "word": "alone",
        "lang": "lat",
        "actual_lang": "eng",
        "etymological_form": None,
        "true_stem": "alone",
        "oblique_stem": None,
        "root_consonants": ["l", "n"],
        "prefixes_real": ["al"],
        "suffixes_real": [],
        "false_prefix_warnings": ["a"],
        "derivational_class": "adjective",
        "is_consonant_stem": False,
        "compound_parts": ["all", "one"],
        "notes": "From Middle English al one (all one, entirely by oneself). Pure English compound; no Latin etymon. Do not strip a- as Latin prefix.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # anesthesia <- بدون  (from Greek an- + aisthesis via Latin)
    {
        "word": "anesthesia",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "anaesthesia",
        "true_stem": "aesthet",
        "oblique_stem": None,
        "root_consonants": ["s", "th", "t"],
        "prefixes_real": ["an"],
        "suffixes_real": ["ia"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_abstract",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Greek anaesthesia = an- (without) + aisthesis (sensation). Prefix an- is genuinely negative. Root aesthet- from aisthanesthai (to perceive).",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # angle <- النقل  (from Latin angulus = corner)
    {
        "word": "angle",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "angulus",
        "true_stem": "angl",
        "oblique_stem": None,
        "root_consonants": ["n", "g", "l"],
        "prefixes_real": [],
        "suffixes_real": ["us"],
        "false_prefix_warnings": ["an"],
        "derivational_class": "noun_abstract",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin angulus (corner, angle), cognate with Greek ankulos (bent). The an- is part of the root, not a negative prefix.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # apterous <- الأبتر  (from Greek a- + pteron = wingless)
    {
        "word": "apterous",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "apterus",
        "true_stem": "pter",
        "oblique_stem": None,
        "root_consonants": ["p", "t", "r"],
        "prefixes_real": ["a"],
        "suffixes_real": ["ous"],
        "false_prefix_warnings": [],
        "derivational_class": "adjective",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Greek apteros = a- (without) + pteron (wing). Prefix a- is genuinely privative. Root pter- from pteron (wing).",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # aunte <- عمّة  (from Old French ante, from Latin amita = paternal aunt)
    {
        "word": "aunte",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "amita",
        "true_stem": "amit",
        "oblique_stem": None,
        "root_consonants": ["m", "t"],
        "prefixes_real": [],
        "suffixes_real": ["a"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "Archaic/Old French spelling of 'aunt'. From Latin amita (paternal aunt). The -nt- in Old French ante is a phonological development from amita.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # autogenous <- ذاتي  (from Greek autos + genos via Latin)
    {
        "word": "autogenous",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "autogenus",
        "true_stem": "gen",
        "oblique_stem": None,
        "root_consonants": ["g", "n"],
        "prefixes_real": ["auto"],
        "suffixes_real": ["ous"],
        "false_prefix_warnings": [],
        "derivational_class": "adjective",
        "is_consonant_stem": False,
        "compound_parts": ["autos", "genos"],
        "notes": "From Greek autos (self) + genos (birth, origin). Prefix auto- is genuinely present. Root gen- from genos/genesthai (to be born).",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # banner <- علم  (from Old French baniere, Medieval Latin baneria)
    {
        "word": "banner",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "baneria",
        "true_stem": "bann",
        "oblique_stem": None,
        "root_consonants": ["b", "n"],
        "prefixes_real": [],
        "suffixes_real": ["eria"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Old French baniere, from Medieval Latin baneria, from Frankish *bando (sign). Root bann-/band-.",
        "confidence": "moderate",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # bazaar <- بِذار  (Persian origin, entered Western languages via Italian)
    {
        "word": "bazaar",
        "lang": "lat",
        "actual_lang": "other",
        "etymological_form": None,
        "true_stem": "bazaar",
        "oblique_stem": None,
        "root_consonants": ["b", "z", "r"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "noun_place",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Persian bazar (market). Entered European languages via Turkish and Italian. No Latin etymon; gold file labels as lat but origin is Persian.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # bricuis <- مبرقع  (rare/obscure Latin-like form; possibly a hapax)
    {
        "word": "bricuis",
        "lang": "lat",
        "actual_lang": "lat",
        "etymological_form": "bricuis",
        "true_stem": "bricui",
        "oblique_stem": None,
        "root_consonants": ["b", "r", "k"],
        "prefixes_real": [],
        "suffixes_real": ["s"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "Rare or hapax Latin form, possibly related to braccae (trousers/breeches). The Arabic source مبرقع (veiled) suggests a garment association.",
        "confidence": "moderate",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # bruise <- بروز  (from Old French bruisier; root ultimately Germanic)
    {
        "word": "bruise",
        "lang": "lat",
        "actual_lang": "eng",
        "etymological_form": None,
        "true_stem": "bruis",
        "oblique_stem": None,
        "root_consonants": ["b", "r", "s"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "verb",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Old French bruisier (to break), of Germanic origin. Not from Latin; gold file labels as lat but this is Germanic/English.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # buxema <- أبو  (obscure; possibly a proper name or regional form)
    {
        "word": "buxema",
        "lang": "lat",
        "actual_lang": "other",
        "etymological_form": None,
        "true_stem": "buxem",
        "oblique_stem": None,
        "root_consonants": ["b", "k", "s", "m"],
        "prefixes_real": [],
        "suffixes_real": ["a"],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "Obscure form; possibly a proper name or place name. Arabic source أبو (father of) suggests a kunya construction. Etymology uncertain.",
        "confidence": "moderate",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # cachinnate <- القهقهة  (from Latin cachinnare = to laugh loudly)
    {
        "word": "cachinnate",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "cachinnare",
        "true_stem": "cachinn",
        "oblique_stem": None,
        "root_consonants": ["k", "n"],
        "prefixes_real": [],
        "suffixes_real": ["are"],
        "false_prefix_warnings": [],
        "derivational_class": "verb",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin cachinnare (to laugh loudly, to guffaw), an onomatopoeic word. The doubled -nn- is part of the root, not a suffix.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # cartridge <- خرطوشة  (from French cartouche, from Latin charta = paper)
    {
        "word": "cartridge",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "charta",
        "true_stem": "chart",
        "oblique_stem": None,
        "root_consonants": ["k", "r", "t"],
        "prefixes_real": [],
        "suffixes_real": ["a"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From French cartouche, from Italian cartoccio, from Latin charta (paper, from Greek kharte). A cartridge was originally a paper roll containing powder.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # cavalier <- حصان  (from French cavalier, from Latin caballus = horse)
    {
        "word": "cavalier",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "caballus",
        "true_stem": "caball",
        "oblique_stem": None,
        "root_consonants": ["k", "b", "l"],
        "prefixes_real": [],
        "suffixes_real": ["us"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From French cavalier, from Italian cavaliere, from Late Latin caballarius (horseman), from caballus (horse). Root caball-.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # cephalalgia <- وجع  (from Greek kephale + algos via Latin)
    {
        "word": "cephalalgia",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "cephalalgia",
        "true_stem": "cephal",
        "oblique_stem": None,
        "root_consonants": ["k", "f", "l"],
        "prefixes_real": [],
        "suffixes_real": ["algia"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_abstract",
        "is_consonant_stem": False,
        "compound_parts": ["kephale", "algos"],
        "notes": "From Greek kephale (head) + algos (pain). Compound: cephal- (head) + -algia (pain suffix). Medical Latin term for headache.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # esther <- عشتار  (proper name; from Hebrew/Semitic Ishtar)
    {
        "word": "esther",
        "lang": "lat",
        "actual_lang": "heb",
        "etymological_form": None,
        "true_stem": "esther",
        "oblique_stem": None,
        "root_consonants": ["s", "th", "r"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Hebrew Esther, cognate with Babylonian Ishtar (goddess). Arabic عشتار is also a direct borrowing from the same Mesopotamian root. Semitic proper name, not Latin.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # europe <- الغروب  (from Greek Europa via Latin)
    {
        "word": "europe",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "Europa",
        "true_stem": "europ",
        "oblique_stem": None,
        "root_consonants": ["r", "p"],
        "prefixes_real": [],
        "suffixes_real": ["a"],
        "false_prefix_warnings": ["eu"],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin Europa, from Greek Europe, possibly from Semitic ereb (sunset, west; cf. Arabic غروب). The eu- is not the Greek prefix eu- (well) but part of the proper name root.",
        "confidence": "moderate",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # fungus <- إسفنجي  (from Latin fungus; cognate with Greek spongos)
    {
        "word": "fungus",
        "lang": "lat",
        "actual_lang": "lat",
        "etymological_form": "fungus",
        "true_stem": "fung",
        "oblique_stem": None,
        "root_consonants": ["f", "n", "g"],
        "prefixes_real": [],
        "suffixes_real": ["us"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin fungus (mushroom), possibly cognate with Greek spongos (sponge). 2nd-declension noun. Root fung-.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # gala <- خِلعة  (from Old French gale, possibly of Germanic origin)
    {
        "word": "gala",
        "lang": "lat",
        "actual_lang": "other",
        "etymological_form": None,
        "true_stem": "gala",
        "oblique_stem": None,
        "root_consonants": ["g", "l"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "noun_abstract",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Old French gale (rejoicing), possibly of Germanic origin. Some link to Arabic khil'a (robe of honor/gala dress). Not directly from Latin.",
        "confidence": "moderate",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # heinous <- مهين  (from Old French haineus, from haïr = to hate)
    {
        "word": "heinous",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "odiosus",
        "true_stem": "hain",
        "oblique_stem": None,
        "root_consonants": ["h", "n"],
        "prefixes_real": [],
        "suffixes_real": ["ous"],
        "false_prefix_warnings": [],
        "derivational_class": "adjective",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Old French haineus (hateful), from haïr (to hate), of Germanic origin. Not directly from Latin; entered English via French. Gold labels as lat.",
        "confidence": "moderate",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # honour <- التكريم  (from Old French honor, from Latin honor)
    {
        "word": "honour",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "honor",
        "true_stem": "honor",
        "oblique_stem": "honos",
        "root_consonants": ["n", "r"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "noun_abstract",
        "is_consonant_stem": True,
        "compound_parts": None,
        "notes": "From Latin honor/honos (esteem, dignity). 3rd-declension: nom. honor, gen. honor-is. Root honor-/honos-.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # horticulture <- خريف  (from Latin hortus + cultura)
    {
        "word": "horticulture",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "horticultura",
        "true_stem": "hort",
        "oblique_stem": None,
        "root_consonants": ["r", "t"],
        "prefixes_real": [],
        "suffixes_real": ["cultura"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_abstract",
        "is_consonant_stem": False,
        "compound_parts": ["hortus", "cultura"],
        "notes": "From Latin hortus (garden) + cultura (cultivation). Compound: horti- (garden genitive) + culture. Root hort- from hortus.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # hyaline <- خيال  (from Greek hyalos = glass, via Latin hyalinus)
    {
        "word": "hyaline",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "hyalinus",
        "true_stem": "hyal",
        "oblique_stem": None,
        "root_consonants": ["h", "l"],
        "prefixes_real": [],
        "suffixes_real": ["inus"],
        "false_prefix_warnings": [],
        "derivational_class": "adjective",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin hyalinus, from Greek hyalinos (glassy), from hyalos (glass or crystal). Root hyal- from Greek hyalos.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # immunization <- إمنع  (from Latin immunis = exempt)
    {
        "word": "immunization",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "immunis",
        "true_stem": "mun",
        "oblique_stem": None,
        "root_consonants": ["m", "n"],
        "prefixes_real": ["im"],
        "suffixes_real": ["ization"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_abstract",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin immunis = im- (not) + munis (serving, bound by duty), from munus (duty, service). Prefix im- is genuinely negative. Root mun- from munus.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # insulin <- إنسولين  (from Latin insula = island; Langerhans islets)
    {
        "word": "insulin",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "insula",
        "true_stem": "insul",
        "oblique_stem": None,
        "root_consonants": ["n", "s", "l"],
        "prefixes_real": [],
        "suffixes_real": ["in"],
        "false_prefix_warnings": ["in"],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "Coined 1922 from Latin insula (island), referring to islets of Langerhans in the pancreas. The in- is NOT the Latin negative prefix; it is the root insula- (island).",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # lake <- لُجّة  (from Latin lacus = lake)
    {
        "word": "lake",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "lacus",
        "true_stem": "lac",
        "oblique_stem": None,
        "root_consonants": ["l", "k"],
        "prefixes_real": [],
        "suffixes_real": ["us"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_place",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin lacus (lake, hollow, pit). 4th-declension noun. Root lac-.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # lave <- ليّف  (from Latin lavare = to wash)
    {
        "word": "lave",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "lavare",
        "true_stem": "lav",
        "oblique_stem": None,
        "root_consonants": ["l", "v"],
        "prefixes_real": [],
        "suffixes_real": ["are"],
        "false_prefix_warnings": [],
        "derivational_class": "verb",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin lavare (to wash). Root lav- from the same PIE root as English 'lather'.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # lazour <- الزفير  (archaic/variant of azure; from Arabic via Latin lazur)
    {
        "word": "lazour",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "lazulum",
        "true_stem": "lazur",
        "oblique_stem": None,
        "root_consonants": ["l", "z", "r"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "Archaic variant of 'azure'. From Medieval Latin lazulum, from Arabic lazaward (lapis lazuli), from Persian Lajward (a region). Root lazur-.",
        "confidence": "moderate",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # linda <- ليّنة  (from Germanic lind = gentle; not Latin)
    {
        "word": "linda",
        "lang": "lat",
        "actual_lang": "other",
        "etymological_form": None,
        "true_stem": "linda",
        "oblique_stem": None,
        "root_consonants": ["l", "n", "d"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Germanic lind (gentle, soft) or Spanish linda (beautiful). Not from Latin, though Spanish linda uses the Latin feminine -a ending. Semitic cognate via Arabic لينة (soft).",
        "confidence": "moderate",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # liter <- ميزان  (from French litre, from Medieval Latin litra)
    {
        "word": "liter",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "litra",
        "true_stem": "litr",
        "oblique_stem": None,
        "root_consonants": ["l", "t", "r"],
        "prefixes_real": [],
        "suffixes_real": ["a"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From French litre, from Medieval Latin litra, from Greek litra (a Sicilian monetary unit). Root litr-.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # mime <- إيماء  (from Latin mimus, from Greek mimos = imitator)
    {
        "word": "mime",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "mimus",
        "true_stem": "mim",
        "oblique_stem": None,
        "root_consonants": ["m"],
        "prefixes_real": [],
        "suffixes_real": ["us"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin mimus, from Greek mimos (imitator, mime actor). Reduplicated onomatopoeic root mim-.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # nyla <- نائلة  (proper name; from Arabic/Semitic origin)
    {
        "word": "nyla",
        "lang": "lat",
        "actual_lang": "other",
        "etymological_form": None,
        "true_stem": "nyla",
        "oblique_stem": None,
        "root_consonants": ["n", "l"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Arabic Naila/Nailah (نائلة, she who attains). Proper name of Semitic origin, not Latin.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # omni <- عمومي  (from Latin omnis = all)
    {
        "word": "omni",
        "lang": "lat",
        "actual_lang": "lat",
        "etymological_form": "omnis",
        "true_stem": "omni",
        "oblique_stem": None,
        "root_consonants": ["m", "n"],
        "prefixes_real": [],
        "suffixes_real": ["s"],
        "false_prefix_warnings": [],
        "derivational_class": "adjective",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin omnis (all, every). Used as a combining form omni- in English scientific vocabulary. Root omni-/omn-.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # ossifier <- عُصّ  (from Latin os/ossis = bone)
    {
        "word": "ossifier",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "os",
        "true_stem": "oss",
        "oblique_stem": "oss",
        "root_consonants": ["s"],
        "prefixes_real": [],
        "suffixes_real": ["ifier"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": True,
        "compound_parts": None,
        "notes": "From Latin os (bone), gen. ossis. 3rd-declension consonant stem: nom. os, gen. oss-is. Ossifier = agent that converts to bone. Root oss-.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # ounce <- أوقية  (from Old French unce, from Latin uncia = twelfth part)
    {
        "word": "ounce",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "uncia",
        "true_stem": "unci",
        "oblique_stem": None,
        "root_consonants": ["n", "k"],
        "prefixes_real": [],
        "suffixes_real": ["ia"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_abstract",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Old French unce, from Latin uncia (a twelfth part of a pound or foot). Also the source of 'inch'. Root unci-.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # rihanna <- ريحانة  (proper name; from Arabic rayhana = sweet basil)
    {
        "word": "rihanna",
        "lang": "lat",
        "actual_lang": "other",
        "etymological_form": None,
        "true_stem": "rihanna",
        "oblique_stem": None,
        "root_consonants": ["r", "h", "n"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Arabic ريحانة (rayhana, sweet basil). Semitic proper name, not Latin.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # romeo <- روماني  (proper name; from Latin Romaeus = pilgrim to Rome)
    {
        "word": "romeo",
        "lang": "lat",
        "actual_lang": "lat",
        "etymological_form": "Romaeus",
        "true_stem": "rom",
        "oblique_stem": None,
        "root_consonants": ["r", "m"],
        "prefixes_real": [],
        "suffixes_real": ["aeus"],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin Romaeus (pilgrim to Rome) or from Roma (Rome). Italian proper name used in Shakespeare. Root rom- from Roma.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # sabrina <- صابرين  (proper name; Celtic river name, Latinized as Sabrina)
    {
        "word": "sabrina",
        "lang": "lat",
        "actual_lang": "lat",
        "etymological_form": "Sabrina",
        "true_stem": "sabrin",
        "oblique_stem": None,
        "root_consonants": ["s", "b", "r", "n"],
        "prefixes_real": [],
        "suffixes_real": ["a"],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "Latin name for the River Severn (Celtic origin, Latinized). Used as a female proper name since Roman times. Arabic صابرين (patient ones) is a coincidental phonetic similarity.",
        "confidence": "moderate",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # salome <- سلمى  (proper name; from Hebrew Shalom = peace)
    {
        "word": "salome",
        "lang": "lat",
        "actual_lang": "heb",
        "etymological_form": None,
        "true_stem": "salom",
        "oblique_stem": None,
        "root_consonants": ["s", "l", "m"],
        "prefixes_real": [],
        "suffixes_real": ["e"],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Hebrew Shalom (peace), feminine form Shlomit. Greek/Latin Salome is the Hellenized form. Arabic سلمى (salma) shares the same Semitic root SLM (peace).",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # scirrhous <- صخري  (from Greek skirros = hard tumor, via Latin scirrhus)
    {
        "word": "scirrhous",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "scirrhus",
        "true_stem": "scirrh",
        "oblique_stem": None,
        "root_consonants": ["s", "k", "r"],
        "prefixes_real": [],
        "suffixes_real": ["ous"],
        "false_prefix_warnings": [],
        "derivational_class": "adjective",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin scirrhus, from Greek skirros (hard tumor). Relating to a hard fibrous carcinoma. Root scirrh- from Greek skirros.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # scylla <- الثكلى  (Greek mythological name, Latinized as Scylla)
    {
        "word": "scylla",
        "lang": "lat",
        "actual_lang": "lat",
        "etymological_form": "Scylla",
        "true_stem": "scyll",
        "oblique_stem": None,
        "root_consonants": ["s", "k", "l"],
        "prefixes_real": [],
        "suffixes_real": ["a"],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "Latin form of Greek Skylla, a sea monster in the Odyssey. The Arabic source الثكلى (the bereaved woman) may suggest a folk etymology. Proper mythological name.",
        "confidence": "moderate",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # senile <- مُسِن  (from Latin senilis = of old age, from senex = old man)
    {
        "word": "senile",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "senilis",
        "true_stem": "sen",
        "oblique_stem": None,
        "root_consonants": ["s", "n"],
        "prefixes_real": [],
        "suffixes_real": ["ilis"],
        "false_prefix_warnings": [],
        "derivational_class": "adjective",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin senilis (of old age), from senex (old man). Root sen- from senex, cognate with Greek geron.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # sephora <- صفورة  (proper name; from Hebrew Tzipporah = bird)
    {
        "word": "sephora",
        "lang": "lat",
        "actual_lang": "heb",
        "etymological_form": None,
        "true_stem": "sephor",
        "oblique_stem": None,
        "root_consonants": ["s", "f", "r"],
        "prefixes_real": [],
        "suffixes_real": ["a"],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Hebrew Tzipporah (bird). Greek/Latin Sephora is the Hellenized form of the name of Moses's wife. Arabic صفورة is a direct transliteration.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # sewer <- إقصاء  (from Old French seuwiere, from Latin ex + aquaria)
    {
        "word": "sewer",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "exaquaria",
        "true_stem": "aqu",
        "oblique_stem": None,
        "root_consonants": ["k", "w"],
        "prefixes_real": ["ex"],
        "suffixes_real": ["aria"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": ["ex", "aquaria"],
        "notes": "From Anglo-French seuwiere (overflow channel), from Latin ex- (out) + aquaria (water channel), from aqua (water). Root aqu- from aqua.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # shakira <- الشاكرة  (proper name; from Arabic shakir = grateful)
    {
        "word": "shakira",
        "lang": "lat",
        "actual_lang": "other",
        "etymological_form": None,
        "true_stem": "shakir",
        "oblique_stem": None,
        "root_consonants": ["sh", "k", "r"],
        "prefixes_real": [],
        "suffixes_real": ["a"],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Arabic الشاكرة (al-shakira, the grateful one), feminine of shakir. Semitic proper name, not Latin.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # stove <- صوبة  (from Middle Dutch or MLG stove; Germanic origin)
    {
        "word": "stove",
        "lang": "lat",
        "actual_lang": "eng",
        "etymological_form": None,
        "true_stem": "stov",
        "oblique_stem": None,
        "root_consonants": ["s", "t", "v"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Middle Dutch or Middle Low German stove (heated room, bathhouse). Germanic origin. Not from Latin; gold file labels as lat but this is Germanic.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # tinnitus <- طنين  (from Latin tinnire = to ring/tinkle)
    {
        "word": "tinnitus",
        "lang": "lat",
        "actual_lang": "lat",
        "etymological_form": "tinnitus",
        "true_stem": "tinnit",
        "oblique_stem": None,
        "root_consonants": ["t", "n"],
        "prefixes_real": [],
        "suffixes_real": ["us"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_abstract",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin tinnitus (a ringing), from tinnire (to ring, tinkle). Onomatopoeic. The doubled -nn- is the root, not a suffix. Arabic طنين (tannin) is a parallel onomatopoeic form.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # toffee <- طيّب  (origin obscure; possibly from tafia, a rum spirit)
    {
        "word": "toffee",
        "lang": "lat",
        "actual_lang": "other",
        "etymological_form": None,
        "true_stem": "toff",
        "oblique_stem": None,
        "root_consonants": ["t", "f"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "Origin disputed; possibly from English dialect taffy or from Caribbean tafia (rum). Not from Latin. Arabic طيّب (pleasant, delicious) may be a semantic parallel.",
        "confidence": "moderate",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # videre <- بصر  (from Latin videre = to see)
    {
        "word": "videre",
        "lang": "lat",
        "actual_lang": "lat",
        "etymological_form": "videre",
        "true_stem": "vid",
        "oblique_stem": None,
        "root_consonants": ["v", "d"],
        "prefixes_real": [],
        "suffixes_real": ["ere"],
        "false_prefix_warnings": [],
        "derivational_class": "verb",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "Latin infinitive videre (to see), from PIE *weid- (to see, to know). Root vid- also appears in video, vision, evident. Arabic بصر (basar = sight) is a semantic parallel.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # visitor <- زائر  (from Latin visitare = to go see)
    {
        "word": "visitor",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "visitare",
        "true_stem": "visit",
        "oblique_stem": None,
        "root_consonants": ["v", "s", "t"],
        "prefixes_real": [],
        "suffixes_real": ["are", "or"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_concrete",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin visitare (to go to see), frequentative of visere (to look at), from videre (to see). Root visit-.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # wane <- ونى  (from Old English wanian = to lessen; Germanic)
    {
        "word": "wane",
        "lang": "lat",
        "actual_lang": "ang",
        "etymological_form": None,
        "true_stem": "wan",
        "oblique_stem": None,
        "root_consonants": ["w", "n"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "verb",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Old English wanian (to lessen, diminish), of Germanic origin. Arabic ونى (wana = to slacken, be tired) may share a proto-Semitic cognate via wandering consonantism.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # zaccai <- زكي  (proper name; from Aramaic/Hebrew Zakkay = pure)
    {
        "word": "zaccai",
        "lang": "lat",
        "actual_lang": "heb",
        "etymological_form": None,
        "true_stem": "zaccai",
        "oblique_stem": None,
        "root_consonants": ["z", "k"],
        "prefixes_real": [],
        "suffixes_real": [],
        "false_prefix_warnings": [],
        "derivational_class": "proper_name",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Aramaic Zakkay / Hebrew Zakkai (pure, innocent), from root ZKK (to be clear/pure). Arabic زكي (zaki = pure) shares the same Semitic root.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
    # zone <- منطقة  (from Latin zona, from Greek zone = belt/girdle)
    {
        "word": "zone",
        "lang": "lat",
        "actual_lang": "lat_via_eng",
        "etymological_form": "zona",
        "true_stem": "zon",
        "oblique_stem": None,
        "root_consonants": ["z", "n"],
        "prefixes_real": [],
        "suffixes_real": ["a"],
        "false_prefix_warnings": [],
        "derivational_class": "noun_abstract",
        "is_consonant_stem": False,
        "compound_parts": None,
        "notes": "From Latin zona, from Greek zone (belt, girdle, zone of the earth). Root zon-.",
        "confidence": "high",
        "annotator": "claude",
        "batch": "batch_5",
    },
]


def main() -> None:
    # Verify count
    assert len(ANNOTATIONS) == 54, f"Expected 54 annotations, got {len(ANNOTATIONS)}"

    # Check no duplicates within batch
    words = [a["word"] for a in ANNOTATIONS]
    assert len(words) == len(set(words)), "Duplicate words in batch_5"

    # Read existing words to avoid double-appending
    existing: set[str] = set()
    if OUTFILE.exists():
        with open(OUTFILE, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    existing.add(json.loads(line)["word"].lower())

    new_annotations = [a for a in ANNOTATIONS if a["word"].lower() not in existing]
    if not new_annotations:
        print("All batch_5 words already present in the file — nothing to append.")
        return

    with open(OUTFILE, "a", encoding="utf-8") as fh:
        for ann in new_annotations:
            fh.write(json.dumps(ann, ensure_ascii=False) + "\n")

    print(f"Appended {len(new_annotations)} annotations to {OUTFILE}")

    # Report total
    total = sum(1 for _ in open(OUTFILE, encoding="utf-8"))
    print(f"Total Layer 1 annotations: {total}")


if __name__ == "__main__":
    main()
